apiVersion: v1
kind: Secret
metadata:
  name: {{ include "osticket.fullname" . }}-mariadb
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: mariadb-password,mariadb-root-password,mariadb-replication-password
data:
  username: osticket