version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:9.1
    volumes:
      - mysql_session_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uptimelabs
      MYSQL_USER: uptimelabs
      MYSQL_PASSWORD: uptimelabs
    ports:
      - "3306:3306"

  app:
    container_name: app
    build:
      context: apps/osticket
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uptimelabs
      MYSQL_USER: uptimelabs
      MYSQL_PASSWORD: uptimelabs

volumes:
  mysql_session_data:
